import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="harlequinn2">
      <div className="container h-full">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main>
        <section>
          <div className="flex flex-row">
            <div className="basis-1/2">
              <h1>Hello, I am a screenprinter</h1>
              <h2>That has a passion for pattern design</h2>
            </div>
            <div className="basis-1/2">
              <p>For me, it is natural and important to seek knowledge and learn new things. That is why I thrive in this industry, where new techniques and effective working methods are constantly updated. My design background in combination with technology has proven successful in previous positions, where my technical interest together with my creative side has been perceived as a strength.</p>

            </div>
          </div>
        </section>
      </main>
      <Footer />
     {/*  <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
      </div>
    </div>
  )
}
