import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className="">
      <div className="container h-full">
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Header />
        <main>
          <section className="">
            <div className="flex flex-row">
              <div className="h-screen basis-1/4 space-y-6">
                <h1>Typography</h1>
                <h1>Design &amp;</h1>
                <h1>Programming</h1>
              </div>
              <div className="basis-1/4">
                <p>For me, it is natural and important to seek knowledge and learn new things. That is why I thrive in this industry, where new techniques and effective working methods are constantly updated. My design background in combination with technology has proven successful in previous positions, where my technical interest together with my creative side has been perceived as a strength.</p>
              </div>
            </div>
            <img src="" alt="" />
          </section>
        </main>
        <Footer />
      </div>
    </div>
  )
}
